# Generated by Django 3.2 on 2021-04-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0009_carspecs_car_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspecs',
            name='car_plan',
        ),
    ]
